services:
  backend:
    build: ./BackEnd
    ports:
      - 8080:8080
    environment:
      - DAD_BACKEND_IP=0.0.0.0

  frontend:
    build: ./FrontEnd
    ports:
      - 80:80
    environment:
      - DAD_WEBSOCKET_IP=127.0.0.1

